services:
  backend:
    build: ./backend
    container_name: daybook-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/daybook
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: daybook-frontend
    restart: always
    ports:
      - "8080:80"   # dùng 8080 thay vì 80 hoặc 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000

  mongo:
    image: mongo:5
    container_name: daybook-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    # không publish port để tránh lộ DB
    # nếu muốn debug có thể mở: "27017:27017"

volumes:
  mongo_data:
