services:
  backend:
    build: ./backend
    container_name: daybook-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/daybook
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: daybook-frontend
    restart: always
    ports:
      - "8080:80"   # bên ngoài 8080, bên trong nginx chạy 80
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://api.ttmmo.com  # trỏ ra backend domain

  mongo:
    image: mongo:5
    container_name: daybook-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    # không cần public port nếu chỉ backend dùng
    # ports:
    #   - "27017:27017"

volumes:
  mongo_data:
