version: "3.9"

services:
  backend:
    build: ./backend
    container_name: daybook-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/daybook
      - JWT_SECRET=your-production-secret-key
      - FRONTEND_URL=https://hai.ttmmo.com
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_BACKEND_URL=https://api.ttmmo.com
    container_name: daybook-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:5
    container_name: daybook-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
